### ISSUE TITLE
Neue Mediathek nicht unterstützt

### ISSUE THREAD

**Issue by morph027** [prof-membrane/plugin.video.zdf_de_lite#3]
SIeht aus, als ob die neue Mediathek so nicht mehr abrufbar ist: https://www.heise.de/newsticker/meldung/ZDF-Mediathek-Neustart-fast-ohne-Probleme-3379515.html

```
18:20:19 T:140001659586304  NOTICE: list
18:20:19 T:140001659586304  NOTICE: check
18:20:23 T:140001659586304  NOTICE: list
18:20:23 T:140001659586304  NOTICE: check
18:20:28 T:140001659586304  NOTICE: list
18:20:28 T:140001659586304  NOTICE: check
18:20:28 T:140001659586304  NOTICE: get url: http://www.zdf.de/ZDFmediathek/xmlservice/web/sendungenAbisZ?characterRangeEnd=N&detailLevel=2&characterRangeStart=N
18:20:28 T:140001659586304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/home/morph/.kodi/addons/plugin.video.zdf_de_lite/default.py", line 4, in <module>
                                                libZdf.list()
                                              File "/home/morph/.kodi/addons/script.module.libZdf/lib/libZdf.py", line 284, in list
                                                libZdfListLetter()
                                              File "/home/morph/.kodi/addons/script.module.libZdf/lib/libZdf.py", line 138, in libZdfListLetter
                                                libZdfListPage('http://www.zdf.de/ZDFmediathek/xmlservice/web/sendungenAbisZ?characterRangeEnd='+letter+'&detailLevel=2&characterRangeStart='+letter)
                                              File "/home/morph/.kodi/addons/script.module.libZdf/lib/libZdf.py", line 167, in libZdfListPage
                                                items = xmlservice.getXML(url)
                                              File "/home/morph/.kodi/addons/script.module.mediathekxmlservice/lib/mediathekxmlservice.py", line 36, in getXML
                                                return listing.getXML(url,type)
                                              File "/home/morph/.kodi/addons/script.module.mediathekxmlservice/lib/listing.py", line 29, in getXML
                                                response = utils.getUrl(url)
                                              File "/home/morph/.kodi/addons/script.module.libZdf/lib/_utils.py", line 12, in getUrl
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
18:20:28 T:140002619898176   ERROR: GetDirectory - Error getting plugin://plugin.video.zdf_de_lite/?mode=libZdfListLetter&name=N&type=dir
18:20:28 T:140002619898176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zdf_de_lite/?mode=libZdfListLetter&name=N&type=dir) failed
18:20:28 T:140001659586304  NOTICE: list
18:20:28 T:140001659586304  NOTICE: check
```

**Comment by jamfx** [comment]
Das ist definitiv der Fall. Die neue Mediathekenstruktur macht das ZDF-Plugin unbrauchbar. Ich kann leider kein schickes Log mitliefern, wie mein vorgänger, aber auch bei mir (Raspi 2B+ mit LibreELEC und Kodi) läuft die Mediathek vom ZDF nicht mehr. :'( Wäre super, wenn das jemand anpassen könnte! Vielen Dank!

**Comment by prof-membrane** [comment]
Ein Update gibt es schon seit heute morgen - aktualisiert doch einfach mal das Add-on...

**Comment by morph027** [comment]
Huh, ich hab das doch gerade eben erst frisch installiert, hätte doch dann die neue sein müssen. Ich schau nochmal.

**Comment by morph027** [comment]
Tatsächlich, bei mir hat das Update der libzdf gefehlt. Danke für die TOP Arbeit, meine Kids freuen sich ;)

**Comment by jamfx** [comment]
Ich habe jetzt die Version 3.0.1 des Membrane ZDF Mediathekenplugins und die Version 1.1.0  des libZdf. Leider läuft es bei mir nicht. Was kann ich noch tun?

**Comment by jamfx** [comment]
Sorry, hab es dann auch gefunden...

**Comment by Klaaner** [comment]
Bei mir wird noch die Version 2.2.2 angezeigt. Diese findet keine Einträge. Auch im[ Kodi Wiki ](http://kodi.wiki/view/Add-on:ZDF_Mediathek)ist noch die 2.2.2 als aktuell angegeben. Wie komme ich an die neue Version? Eiun Update in Kodi bringt auch nur die 2.2.2

**Comment by prof-membrane** [comment]
https://github.com/prof-membrane/repository.membrane
